services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=crm_lite_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434:5432'
